config/routes.rb
Rails.application.routes.draw do
  resources :suppliers
  resources :bikes
  resources :customers
  resources :rents do
    member do
      post :back
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :supplier#, optional: true
  has_many :rents
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :rents
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :bike, optional: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :bikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :find_bike, only:[:edit, :update, :destroy]

  def index
    @bikes = Bike.select('bikes.id, bikeType, quantity, supName').joins(:supplier)
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(clean_params)
    if @bike.save
      redirect_to bikes_path, notice: "新增成功"
    else
      render "new" #new.html.erb
    end
  end

  def edit
  end

  def update
    if @bike.update(clean_params)
      redirect_to bikes_path, notice: "修改成功"
    else
      render "edit"
    end
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path, notice: "刪除完成"
  end

  private
  def clean_params
    params.require(:bike).permit(:bikeNo, :bikeType, :quantity, :supplier_id )
  end

  def find_bike
    @bike = Bike.find_by(id: params[:id])
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :find_customer, only:[:edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def new
   @customer = Customer.new
  end

  def create
    @customer = Customer.new(clean_params)
    if @customer.save
     redirect_to customers_path, notice: "新增成功"
    else
     render "new" #new.html.erb
   end
  end

  def edit
  end

  def update
    if @customer.update(clean_params)
      redirect_to customers_path, notice: "修改成功"
    else
      render "edit"
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_path, notice: "刪除完成"
  end

  private
  def clean_params
    params.require(:customer).permit(:cusNo, :cusName, :cusID, :cusTel)
  end

  def find_customer
    @customer = Customer.find_by(id: params[:id])
  end

end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
    before_action :find_rent, only:[:edit, :update, :destroy, :back]

  def index
    @rents = Rent.select('rents.id, customers.cusName, bikes.bikeType, rents.created_at, backtime, price').joins(:customer, :bike)
  end

  def new
    @rent = Rent.new
  end

  def create
    @rent = Rent.new(clean_params)
    if @rent.save
     redirect_to rents_path, notice: "新增成功"
    else
     render "new" #new.html.erb
    end
  end

  def edit
  end

  def back
    # Time.zone = "Taipei"
    rtime = @rent.created_at
    btime = Time.now
    ttime = (((btime.to_time)-(rtime.to_time)).to_i)/60
    if ttime % 60 == 0
      cost = (ttime/60)*100
    elsif ttime <= 30
      cost = 50
    elsif ttime > 30 && ttime <= 60
      cost = 100
    else
      cost = (ttime/60)*100 + 50
    end
    @rent.update(backtime: Time.now, price: cost)
    redirect_to rents_path, notice: "歸還成功"
  end

  def destroy
    @rent.destroy
    redirect_to rents_path, notice: "刪除完成"
  end

  private
  def clean_params
    params.require(:rent).permit(:customer_id, :bike_id)
  end

  def find_rent
    @rent = Rent.find_by(id: params[:id])
  end

  end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :find_supplier, only:[:edit, :update, :destroy, :show]

  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(clean_params)
    if @supplier.save
      redirect_to suppliers_path, notice: "新增成功"
    else
      render "new" #new.html.erb
    end
  end

  def edit
  end

  def update
    if @supplier.update(clean_params)
      redirect_to suppliers_path, notice: "修改成功"
    else
      render "edit"
    end
  end

  def destroy
    @supplier.destroy
    redirect_to suppliers_path, notice: "刪除完成"
  end

  private
  def clean_params
    params.require(:supplier).permit(:supNo, :supName, :supTel)
  end

  def find_supplier
    @supplier = Supplier.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/bikes/_form.html.erb
<%= simple_form_for bike do |f| %>
  <%= f.input :bikeType, label:'車種型號' %><br />
  <%= f.input :quantity, label:'數量' %><br />
  <%= f.association :supplier, label_method: :supName, value_method: :id, label:'供應商編號' %><br />
  <div style="text-align:center;">
    <%= f.button:submit, "新增車種", class:"btn btn-success btn-lg"%>
    <%= link_to "返回", bikes_path, class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">修改車種資料</h1>
  <div style="font-family:微軟正黑體"><%= render "form", bike: @bike %></div>
</div>

app/views/bikes/index.html.erb
<nav class="navbar navbar-default" style="font-family:微軟正黑體">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">腳踏車租賃系統</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href=rents>租車/還車</a></li>
      <li><a href=customers>會員管理</a></li>
      <li class="active"><a href="#">車輛管理</a></li>
      <li><a href=suppliers>合作供應商</a></li>
    </ul>
  </div>
</nav>

<div class="container">

  <div style="text-align:center; font-family:微軟正黑體"><%= link_to "新增車種", new_bike_path, class: "btn btn-info" %></div></br>
  <table class = "table">
    <thead>
      <tr>
        <td>車種編號</td>
        <td>車種型號</td>
        <td>數量</td>
        <td>供應商</td>
      </tr>
    </thead>
    <tbody>
      <% @bikes.each do |bike| %>
        <tr>
          <td><%= bike.id %></td>
          <td><%= bike.bikeType %></td>
          <td><%= bike.quantity %></td>
          <td><%= bike.supName %></td>
          <td><%= link_to "編輯", edit_bike_path(bike), class: "btn btn-warning" %></td>
          <td><%= link_to "刪除", bike_path(bike), method: "delete", data: {confirm: "Delete it or not?"}, class: "btn btn-danger"%></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>

app/views/bikes/new.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">新增車種</h1>
  <div style="font-family:微軟正黑體"><%= render "form", bike: @bike %></div>
</div>

app/views/customers/_form.html.erb
<%= simple_form_for customer do |f| %>
  <%= f.input :cusName, label: '會員姓名' %><br />
  <%= f.input :cusID, label: '身分證字號' %><br />
  <%= f.input :cusTel, label: '電話' %><br />
  <div style="text-align:center;">
    <%= f.button:submit, "新增會員", class:"btn btn-success btn-lg"%>
    <%= link_to "返回", customers_path, class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">修改會員資料</h1>
  <div style="font-family:微軟正黑體"><%= render "form", customer: @customer %></div>
</div>

app/views/customers/index.html.erb
<nav class="navbar navbar-default" style="font-family:微軟正黑體">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">腳踏車租賃系統</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href=rents>租車/還車</a></li>
      <li class="active"><a href="#">會員管理</a></li>
      <li><a href=bikes>車輛管理</a></li>
      <li><a href=suppliers>合作供應商</a></li>
    </ul>
  </div>
</nav>


<div class="container">

<div style="text-align:center; font-family:微軟正黑體"><%= link_to "新增會員", new_customer_path, class: "btn btn-info" %></div></br>

<table class = "table">
  <thead>
    <tr>
      <td>會員編號</td>
      <td>會員姓名</td>
      <td>身分證字號</td>
      <td>電話</td>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.cusName %></td>
        <td><%= customer.cusID %></td>
        <td><%= customer.cusTel %></td>
        <!--td><%= customer.created_at %></td-->
        <td><%= link_to "編輯", edit_customer_path(customer), class: "btn btn-warning" %></td>
        <td><%= link_to "刪除", customer_path(customer), method: "delete", data: {confirm: "是否刪除此會員？"}, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
  </tfoot>
</table>

</div>

app/views/customers/new.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">新增會員</h1>
  <div style="font-family:微軟正黑體"><%= render "form", customer: @customer %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>腳踏車租借系統</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rents/_form.html.erb
<div style="font-family:微軟正黑體">
  <div class="panel panel-default">
    <div class="panel-body" style="text-align:center;">
        *腳踏車租借：$100/小時，$50/半小時。時間未滿一小時以半小時計費。
    </div>
  </div>
  <%= simple_form_for rent do |f| %>
    <%= f.association :customer, label_method: :cusName, value_method: :id, label:'會員' %><br />
    <%= f.association :bike, label_method: :bikeType, value_method: :id, label:'供應商編號' %><br />
    <div style="text-align:center;">
      <%= f.button:submit, "租借", class:"btn btn-success btn-lg" %>
      <%= link_to "返回", rents_path, class: "btn btn-info btn-lg" %>
    </div>
  <% end %>
</div>

app/views/rents/index.html.erb
<nav class="navbar navbar-default" style="font-family:微軟正黑體">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">腳踏車租賃系統</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">租車/還車</a></li>
      <li><a href=customers>會員管理</a></li>
      <li><a href=bikes>車輛管理</a></li>
      <li><a href=suppliers>合作供應商</a></li>
    </ul>
  </div>
</nav>
<!--div style="text-align:center; font-family:微軟正黑體"><h1>腳踏車租賃系統</h1></div-->

<div class="container">
  <div class="panel panel-default">
    <div class="panel-body" style="text-align:center;">
        *腳踏車租借：$100/小時，$50/半小時。時間未滿一小時以半小時計費。
    </div>
  </div>

  <div style="text-align:center; font-family:微軟正黑體"><%= link_to "租借腳踏車", new_rent_path, class: "btn btn-info" %></div></br>
  <table class = "table">
    <thead>
      <tr>
        <td>會員編號</td>
        <td>車種編號</td>
        <td>借出日期</td>
        <td>歸還日期</td>
        <td>價格</td>
        <td>處理</td>
      </tr>
    </thead>
    <tbody>
      <% @rents.each do |rent| %>
        <tr>
          <td><%= rent.cusName %></td>
          <td><%= rent.bikeType %></td>
          <td><%= rent.created_at %></td>
          <td><%= rent.backtime %></td>
          <td><%= rent.price %></td>
          <% if rent.backtime.nil? %>
            <td><%= link_to "歸還", back_rent_path(rent), method: "post", data: {confirm: "確定已歸還？"}, class: "btn btn-warning" %></td>
            <td><%= link_to "取消租借", rent_path(rent), method: "delete", data: {confirm: "是否取消此次租借？"}, class: "btn btn-danger"%></td>
          <% else %>
              <td></td>
              <td><%= link_to "刪除", rent_path(rent), method: "delete", data: {confirm: "是否刪除此筆紀錄？"}, class: "btn btn-danger"%></td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>

app/views/rents/new.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">租借腳踏車</h1>
  <div style="font-family:微軟正黑體"><%= render "form", rent: @rent %></div>
</div>

app/views/suppliers/_form.html.erb
<%= simple_form_for supplier do |f| %>
  <%= f.input :supName, label: '供應商名稱' %><br />
  <%= f.input :supTel, label: '電話' %><br />
  <div style="text-align:center;">
    <%= f.button:submit, "新增供應商", class:"btn btn-success btn-lg" %>
    <%= link_to "返回", suppliers_path, class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">修改供應商資料</h1>
  <div style="font-family:微軟正黑體"><%= render "form", supplier: @supplier %></div>
</div>

app/views/suppliers/index.html.erb
<nav class="navbar navbar-default" style="font-family:微軟正黑體">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">腳踏車租賃系統</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href=rents>租車/還車</a></li>
      <li><a href=customers>會員管理</a></li>
      <li><a href=bikes>車輛管理</a></li>
      <li class="active"><a href="#">合作供應商</a></li>
    </ul>
  </div>
</nav>

<div class="container">

<div style="text-align:center; font-family:微軟正黑體"><%= link_to "新增供應商", new_supplier_path, class: "btn btn-info" %></div></br>

<table class = "table">
  <thead>
    <tr>
      <td>供應商編號</td>
      <td>供應商名稱</td>
      <td>電話</td>
    </tr>
  </thead>
  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.id %></td>
        <td><%= supplier.supName %></td>
        <td><%= supplier.supTel %></td>
        <td><%= link_to "編輯", edit_supplier_path(supplier), class: "btn btn-warning" %></td>
        <td><%= link_to "刪除", supplier_path(supplier), method: "delete", data: {confirm: "是否刪除此供應商？"}, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
  </tfoot>
</table>

</div>

app/views/suppliers/new.html.erb
<div class="container">
  <h1 style="text-align:center; font-family:微軟正黑體">新增供應商</h1>
  <div style="font-family:微軟正黑體"><%= render "form", supplier: @supplier %></div>
</div>